=== eswdd/cougar/disco-codegen-plugin/src/main/resources/bsidl/v4_0/Interface.xsd
<?xml version="1.0" encoding="UTF-8"?><!--  ~ Copyright 2014, The Sporting Exchange Limited  ~  ~ Licensed under the Apache License, Version 2.0 (the "License");  ~ you may not use this file except in compliance with the License.  ~ You may obtain a copy of the License at  ~  ~     http://www.apache.org/licenses/LICENSE-2.0  ~  ~ Unless required by applicable law or agreed to in writing, software  ~ distributed under the License is distributed on an "AS IS" BASIS,  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~ See the License for the specific language governing permissions and  ~ limitations under the License.  --><!-- Interface Version 4.0 --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">	<xs:include schemaLocation="common.xsd"/>	<xs:include schemaLocation="exceptionType.xsd"/>	<xs:include schemaLocation="dataType.xsd"/>	<xs:include schemaLocation="eventType.xsd"/>	<xs:element name="interface" type="interface-type" nillable="false"/>	<xs:complexType name="interface-type">		<xs:sequence>			<xs:element name="authors" type="authors-type" minOccurs="0"/>			<xs:element name="description" type="description-type" minOccurs="0"/>			<xs:element name="operation" type="operation-type" minOccurs="0" maxOccurs="unbounded"/>			<xs:element name="event" type="event-type" minOccurs="0" maxOccurs="unbounded"/>			<xs:element name="dataType" type="dataType-type" minOccurs="0" maxOccurs="unbounded"/>			<xs:element name="exceptionType" type="exceptionType-type" minOccurs="0" maxOccurs="unbounded"/>			<xs:element name="extensions" type="extension-type" minOccurs="0"/>			<xs:element name="simpleType" type="base-parameter-type" minOccurs="0" maxOccurs="unbounded"/>			<xs:element name="sharedTypes" type="sharedTypes-type" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>		<xs:attribute name="name" type="xs:string" use="required"/>		<xs:attribute name="owner" type="xs:string" use="optional"/>		<xs:attribute name="version" type="version-type" use="required"/>		<xs:attribute name="date" type="xs:string" use="optional"/>		<xs:attribute name="namespace" type="xs:string" use="optional"/>	</xs:complexType>	<xs:complexType name="operation-type">		<xs:sequence>			<xs:element name="description" type="description-type" minOccurs="0"/>			<xs:element name="parameters" type="parameters-type" minOccurs="0"/>			<xs:element name="consumers" type="consumers-type" minOccurs="0"/>			<xs:element name="extensions" type="extension-type" minOccurs="0"/>		</xs:sequence>		<xs:attribute name="name" type="xs:string"/>		<xs:attribute name="since" type="version-type"/>		<xs:attribute name="connected" type="xs:boolean" default="false" use="optional"/>	</xs:complexType>	<xs:complexType name="parameters-type">		<xs:sequence>			<xs:element name="request" type="request-type" minOccurs="0"/>			<xs:element name="simpleResponse" type="response-type" minOccurs="0"/>			<xs:element name="response" type="response-type" minOccurs="0"/>			<xs:element name="exceptions" type="exceptions-type" minOccurs="0"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="request-type">		<xs:sequence>			<xs:element name="parameter" type="extensible-parameter-type" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="response-type">		<xs:sequence>			<xs:element name="description" type="description-type" minOccurs="0"/>            <xs:element name="validValues" type="validValues-type" minOccurs="0"/>		</xs:sequence>		<xs:attribute name="type" type="xs:string" use="required"/>		<xs:attribute name="mandatory" type="xs:boolean" use="optional"/>	</xs:complexType>	<xs:complexType name="consumers-type">		<xs:sequence>			<xs:element name="product" type="product-type" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="product-type">		<xs:simpleContent>			<xs:extension base="xs:string">				<xs:attribute name="name" type="xs:string" use="required"/>			</xs:extension>		</xs:simpleContent>	</xs:complexType>	<xs:complexType name="authors-type">		<xs:sequence>			<xs:element name="author" type="author-type" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="author-type">		<xs:attribute name="name" type="xs:string"/>		<xs:attribute name="email" type="xs:string"/>	</xs:complexType></xs:schema>

=== eswdd/cougar/socket-perf-testing/socket-perf-testing-idd/src/main/resources/SocketPerfTesting.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
  ~ Copyright 2014, The Sporting Exchange Limited
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<interface name="SocketPerfTesting"
            owner="Simon Matic Langford"
            version="1.0"
            namespace="com.betfair.cougar.perf.socket"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		    xsi:noNamespaceSchemaLocation="http://subversion.techops.uk.betfair:8080/svn/Service/Interface/Definition/3.3/Interface.xsd">

	<description></description>

    <operation name="startPushTest" since="1.0.0">
        <description>Start the push test</description>
        <parameters>
            <request>
            </request>
            <response type="void">
                <description></description>
            </response>
        </parameters>
    </operation>

    <operation name="startRpcTest" since="1.0.0">
        <description>Start the rpc test</description>
        <parameters>
            <request>
                <parameter name="length" type="i64" mandatory="true">
                    <description>Time in ms to run the test for</description>
                </parameter>
                <parameter name="numClientThreads" type="i32" mandatory="false">
                    <description>Num threads to use in each client (defaults to 1)</description>
                </parameter>
            </request>
            <response type="void">
                <description></description>
            </response>
        </parameters>
    </operation>

    <operation name="getRpcControl" since="1.0.0" connected="true">
        <description>Get the heap which controls rpc testing on clients</description>
        <parameters>
            <request></request>
            <response type="RpcControl">
                <description></description>
            </response>
        </parameters>
    </operation>

    <operation name="getNumHeapsForTest" since="1.0.0">
        <description>Retrieve a count of the number of heaps to be used by the test (Controlled by the server)</description>
        <parameters>
            <request>
            </request>
            <response type="i32">
                <description>The value of the passed property</description>
            </response>
        </parameters>
    </operation>

    <operation name="noop" since="1.0.0">
        <description>Noop method used for rpc tests</description>
        <parameters>
            <request>
            </request>
            <response type="void">
                <description>void operation</description>
            </response>
        </parameters>
    </operation>

    <operation name="subscribeToHeap" since="1.0.0" connected="true">
        <description>Subscribe to one of the heaps</description>
        <parameters>
            <request>
                <parameter name="heapNumber" mandatory="true" type="i32">
                    <description>The heap to subscribe to (indexed from zero)</description>
                </parameter>
            </request>
            <response type="HeapTester">
                <description>The value of the passed property</description>
            </response>
        </parameters>
    </operation>

	<dataType name="RpcControl">
		<description>Our connected object</description>
        <parameter name="running" type="bool" mandatory="true">
            <description>Whether the test should be running</description>
        </parameter>
		<parameter name="numThreads" type="i32" mandatory="true">
			<description>The number of threads to use in each client</description>
		</parameter>
	</dataType>

	<dataType name="HeapTester">
		<description>Our connected object</description>
        <parameter name="expectedFinalValue" type="i64" mandatory="true">
            <description>The expected final value for the 'value' field on termination of the heap</description>
        </parameter>
		<parameter name="value" type="i64" mandatory="true">
			<description>The value that will be updated during the test</description>
		</parameter>
	</dataType>

    <exceptionType name="SimpleException" prefix="SEX">
   		<!--
   			Cougar currently requires that all Exceptions have a first parameter
   			that is defined by its valid values, all defined by an incrementing id
   		-->
   		<description>This exception is thrown when an operation fails</description>
   		<parameter name="errorCode" type="string">
   			<description>the unique code for this error</description>
   			<validValues>
   				<value id="1" name="GENERIC">
   					<description>Generic Error</description>
   				</value>
   			</validValues>
   		</parameter>
   	</exceptionType>

</interface>
